name: Default workflow (npm ci, npm test)

on:
  push:
    branches:
      - master

jobs:
  default-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: ./default
