name: Pull request (npm ci, npm test)

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    steps:
      - uses: ./default

      - uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "npm test"
